server:
  port: 8991
spring:
  profiles:
    active: dev
  application:
    name: markdown-server
  servlet:
    multipart:
      enabled: true
      # 默认文件上传限制给大一点，在代码中在控制一下
      max-file-size: 1GB
      max-request-size: 3GB

file:
  markdown: /docker/cloud-markdown/data/static/markdown/
  image: /markdown/data/static/image/